name: I am Ben
favicon: null
layout_spectrum: 0.9126416181679815
typography_spectrum: 0.8283264916390181
title: I am Ben
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0
  lightness: 0.729953860398382
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
